export const COMMON = {
  ALERT_MESSAGE: "ALERT_MESSAGE",
  LOADING: "LOADING",
  STATISTIC_CURRENT_TAB: "STATISTIC_CURRENT_TAB",
  STATISTIC_REPORT_CURRENT_TAB: "STATISTIC_REPORT_CURRENT_TAB",
  USER_MANAGEMENT_CURRENT_TAB: "USER_MANAGEMENT_CURRENT_TAB",
  USER_PERMISSION_CURRENT_TAB: "USER_PERMISSION_CURRENT_TAB",
  REPORT_DETAIL_CURRENT_TAB: "REPORT_DETAIL_CURRENT_TAB",
  DATA_SRC_CURRENT_TAB: "DATA_SRC_CURRENT_TAB",
  IS_STICKY_BTN: "IS_STICKY_BTN",
  JOB_PROPOSAL_CURRENT_TAB: "JOB_PROPOSAL_CURRENT_TAB",
};
